# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Open Field Journal
tagline:          'Open Science'
description:      'Brian Geyer&#39;s preliminary analyses of his collected dissertation data, from the field.'
#baseurl:          '/open-field-journal'

author:
  name:           'Brian Geyer'
  url:            https://twitter.com/GeyerBrian

paginate:         5
  paginate_path:    '/blog/page:num'

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.5.3
sidebar_home_link:  true
  sidebar_blog_link:  '/blog'   
                                # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/geyerbri/open-field-journal
