# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            open field journal
tagline:          'Open Science'
description:      'Brian Geyer&#39;s preliminary analyses of his collected dissertation data, from the field.'
url:          	  https://geyerbri.github.io/open-field-journal
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Brian Geyer'
  url:            https://twitter.com/GeyerBrian

paginate:         5
paginate_path:    '/blog/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.5.3
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   
                                # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/fongandrew/hydeout
